#!/bin/bash
function getCurBranch(){
    echo $(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
}

branch=$(getCurBranch)
git config -f .gitmodules submodule.sedona.branch $branch

cd sedona
git stash push
git checkout $branch || git checkout -b $branch && git push --set-upstream origin $branch
git stash apply
git add .
echo Enter commit message:
read commitMsg
git commit -m "$commitMsg"
cd ..
