#!/bin/bash
function getCurBranch(){
    echo $(git branch | sed -n -e 's/^\* \(.*\)/\1/p')
}

branch=$(getCurBranch)
git config -f .gitmodules submodule.sedona.branch $branch

git stash push
git checkout $branch || git checkout -b $branch
git push || git push --set-upstream origin $branch
git stash apply
git add .
echo Enter commit message:
read commitMsg
git commit -m "$commitMsg"
git push

